# Generated by Django 5.1.3 on 2024-12-22 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('course_period', models.DateTimeField(verbose_name='class period')),
                ('course_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('std_uid', models.IntegerField(primary_key=True, serialize=False)),
                ('std_name', models.CharField(max_length=50)),
                ('std_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_uid', models.IntegerField(primary_key=True, serialize=False)),
                ('Grade', models.IntegerField()),
                ('Course_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_checkin.course')),
                ('Student_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_checkin.student')),
            ],
        ),
    ]
