# Generated by Django 5.1.3 on 2025-01-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_checkin', '0002_remove_course_course_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='Grade',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
